<?php
require_once('../Views/template/header.phtml'); ?>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel='stylesheet' type='text/css' href='../css/admin.css'/>

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <div class="categoryBackground">
            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="inputCategory">Category Name</label>
                            <input name="categoryName" value="<?php if (isset($_POST['categoryName'])) {echo $_POST['categoryName']; 	} ?>" required type="text" class="form-control" id="inputCategory" placeholder="Enter category">
                        </div>
                        <div class="form-group">
                            <label for="inputCategoryCode">Category code</label>
                            <input name="categoryCode" value="<?php if (isset($_POST['categoryCode'])) {echo $_POST['categoryCode']; 	} ?>" required type="text" class="form-control"  id="inputCategoryCode" placeholder="Enter category code">
                        </div>
                        <button type="submit" name="makeCategory" class="btn btn-primary">Submit</button>
                    </div>

                </div>
            </div>
        </div>
    </form>

<?php require_once('../Views/template/footer.phtml');
