<?php
require_once('../Views/template/header.phtml'); ?>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel='stylesheet' type='text/css' href='../css/admin.css'/>

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <div class="flagBackground">
            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="inputFlag">Create a new flag</label>
                            <input name="flagDescription" value="<?php if (isset($_POST['flagDescription'])) {echo $_POST['flagDescription']; 	} ?>" required type="text" class="form-control" id="inputFlag" placeholder="Enter the description for the flag">
                        </div>
                        <button type="submit" name="makeFlag" class="btn btn-primary">Submit</button>
                    </div>

                </div>
            </div>
        </div>
    </form>

<?php require_once('../Views/template/footer.phtml');
