<?php
    require_once('../Views/template/header.phtml'); ?>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel='stylesheet' type='text/css' href='../css/scoringAndQuestioningStyle.php'/>

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        So this will be the create client page. As you can see, there's nothing to see
    </form>

<?php require_once('../Views/template/footer.phtml');
