<?php
if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'A')) {
require_once('../Views/template/header.phtml'); ?>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel='stylesheet' type='text/css' href='../css/admin.css'/>

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <div class="questionBackground">
            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="selectSubCategory">Select a Sub-Category:</label>
                            <select id="selectSubCategory" name="selectSubCategory" required class="form-control long" data-live-search="true">
                                <?php $categories = $questionInfo['questionsAndCategories'];
                                foreach ($categories as $category) { ?>
                                <optgroup label="<?php echo $category['catDescription']; ?>">
                                   <?php $subCategories = $category['subCategories'];
                                   foreach ($subCategories as $subCategory) { ?>
                                    <option value="<?php echo $subCategory['subCatID']; ?>"><?php echo $subCategory['subCatDescription']; ?></option>
                                    <?php } ?>
                                </optgroup>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="inputQuestion">Write the question:</label>
                            <input name="questionContent" value="<?php if (isset($_POST['questionContent'])) {echo $_POST['questionContent']; 	} ?>" required type="text" class="form-control"  id="inputQuestion" placeholder="Enter the question">
                        </div>
                        <div class="form-group">
                            <label for="mark1">Score of 1:</label>
                            <input name="mark1" value="<?php if (isset($_POST['mark1'])) {echo $_POST['mark1']; 	} ?>"  required type="text" class="form-control" id="mark1" placeholder="Write the guideline for the score here">
                        </div>
                        <div class="form-group">
                            <label for="mark2">Score of 2:</label>
                            <input name="mark2" value="<?php if (isset($_POST['mark2'])) {echo $_POST['mark2']; 	} ?>"  required type="text" class="form-control" id="mark2" placeholder="Write the guideline for the score here">
                        </div>
                        <div class="form-group">
                            <label for="mark3">Score of 3:</label>
                            <input name="mark3" value="<?php if (isset($_POST['mark3'])) {echo $_POST['mark3']; 	} ?>"  required type="text" class="form-control" id="mark3" placeholder="Write the guideline for the score here">
                        </div>
                        <div class="form-group">
                            <label for="mark4">Score of 4:</label>
                            <input name="mark4" value="<?php if (isset($_POST['mark4'])) {echo $_POST['mark4']; 	} ?>"  required type="text" class="form-control" id="mark4" placeholder="Write the guideline for the score here">
                        </div>
                        <div class="form-group">
                            <label for="mark5">Score of 5:</label>
                            <input name="mark5" value="<?php if (isset($_POST['mark5'])) {echo $_POST['mark5']; 	} ?>"  required type="text" class="form-control" id="mark5" placeholder="Write the guideline for the score here">
                        </div>
                        <button type="submit" name="makeQuestion" class="btn btn-primary">Submit</button>
                    </div>

                </div>
            </div>
        </div>
    </form>

<?php require_once('../Views/template/footer.phtml');
}