<?php
require_once('../Views/template/header.phtml'); ?>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel='stylesheet' type='text/css' href='../css/admin.css'/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <script> $('select').selectpicker(); </script>

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <?php  $auditInfo = $view->auditInfo; ?>
        <div class="auditBackground">
            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="selectClient"> Client: </label>
                            <?php $clients = $auditInfo['clients']; ?>
                           <select id="selectClient"  class="form-control" name="clientID" required>
                                <option value="" selected disabled>Please select a client</option>
                               <?php foreach ($clients as $client) { ?>
                                <option title="" value="<?php echo $client['userID']?>"><?php echo $client['username']?></option>
                                <?php } ?>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="inputLocation"> Location: </label>
                        <input name="location" value="<?php if (isset($_POST['location'])) {echo $_POST['location']; 	} ?>" required type="text" class="form-control"  id="inputLocation" placeholder="Enter location of audit">
                        </div>
                        <?php $categories = $auditInfo['questionsAndCategories']; ?>
                        <div class="row">
                            <div class="col-sm-2"></div>
                        <div class="form-group col-sm-8">
                            <label for="inputLocation"> Select questions for the audit: </label>
                            <?php $count= 0;
                            $questionIDCount = 0;
                            foreach ($categories as $category) {
                                $subCategories = $category['subCategories']; ?>
                                <h5><strong>Category: <?php echo $category['catDescription']; ?></strong></h5>
                              <?php  foreach ($subCategories as $subCategory) {
                                    $count = $count + 1;
                                    $questions = $subCategory['questions']; ?>

                                    <p> <strong>Sub-Category: <?php echo $subCategory['subCatDescription']; ?></strong></p>
                                    <div class="row">
                                        <div class="col-sm-4">
                                    <label for="auditQuestions">Audit Questions:</label>
                                        </div>
                                    <div class="col-sm-8">
                                        <select id="auditQuestions" name="questionID" class="selectpicker long" multiple data-live-search="true" >
                                            <option value="" disabled >Choose audit questions</option>
                                            <?php foreach ($questions as $question) {
                                                $questionIDCount++;?>
                                                <option title="" value="<?php echo $question['questionID']?>"><?php echo $question['questionContent']; ?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-4">
                                    <label for="questionFlags">Flag Questions:</label>
                                        </div>
                                        <div class="col-sm-8">
                                            <select id="questionFlags" name="selectQuestionsToFlag<?php echo $count?>" class="selectpicker long" data-live-search="true" >
                                                <option value="" selected></option>
                                                <?php foreach ($questions as $question) { ?>
                                                    <option title="" value="<?php echo $question['questionID']  ?>"><?php echo $question['questionContent']; ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-4">
                                            <label for="questionFlagDesc">Flag Description:</label>
                                        </div>
                                        <div class="col-sm-8">
                                            <textarea class="form-control z-depth-1" id="questionFlagDesc"
                                                      name="inputQuestionFlagDesc<?php echo $count; ?>" rows="3"
                                                      placeholder="Write a legal problem with this question"></textarea>
                                        </div>
                                    </div>

                                    <?php
                                }
                            }?>

                        </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-8"></div>
                            <div class="col-sm-2">
                                <input hidden type="text" name="questionIDCount" value="<?php echo $questionIDCount ?>">
                        <button type="submit" name="createAudit" class="btn btn-primary ">Submit</button>
                    </div>
                            <div class="col-sm-2">
                    </div>

                </div>
            </div>
        </div>
    </form>

<?php require_once('../Views/template/footer.phtml');
