<?php
if(!isset($_SESSION['loggedIn']))
{ ?>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!------ Include the above in your HEAD tag ---------->

    <html lang="en">
    <head>
        <title>Login</title>
        <!--Made with love by Mutiullah Samim -->

        <!--Bootsrap 4 CDN-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!--Fontawesome CDN-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

        <!--Custom styles-->
        <link rel="stylesheet" type="text/css" href="/css/login.css">
    </head>
    <body>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>"  method="post">
        <div class="container">
            <div class="d-flex justify-content-center h-100">
                <div class="card">
                    <div class="card-header">
                        <img id=" logo" src="/images/addenergylogo.png" width="65" height="65" alt="Add Energy Logo">
                        <h3>Sign In</h3>

                        <!----- <div class="d-flex justify-content-end social_icon">
                            <a href="https://www.facebook.com/AddEnergyGroup/"><span><i class="fab fa-facebook-square"></i></span></a>
                            <a href="https://www.youtube.com/channel/UCurfzdwCgigJRaIZoFDayZg"><span><i class="fab fa-youtube-square"></i></span></a>
                            <a href="https://twitter.com/add_energy?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><span><i class="fab fa-twitter-square"></i></span></a>
                        </div> ---->
                    </div>
                    <div class="card-body">
                        <form>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="username" name="username" value="<?php if (isset($_POST['username'])) {echo $_POST['username']; 	} ?>">

                            </div>
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                <input type="password" class="form-control" placeholder="password" name="password" value="<?php if (isset($_POST['password'])) {echo $_POST['password']; 	} ?>">
                            </div>
                            <div class="form-group">
                                <?php if (isset($view->loginError)) : ?>
                                    <p id="errormessage"><?php echo $view->loginError; ?></p>
                                <?php endif; ?>
                            </div>
                            <div class="form-group">
                                <input name="submit" type="submit" value="Login" class="btn float-right login_btn">
                            </div>
                            <br/>
                            <br/>

                        </form>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-center">
                            <a href="#">Forgot your password?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </body>
    </html>

<?php }
//Client page
if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'C'))
{
    require_once('Views/template/header.phtml'); ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <div class="container">
        <h2>Audit Reports:</h2>

        <?php
        $clientAudits = $view->clientAudits;
        var_dump($clientAudits);
        $clientID = $view->clientID;
        var_dump($clientID);
        foreach ($clientAudits as $ca)
        { ?>
            <form action="../Controllers/report.php" method="post">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><?php echo $ca['location'];?></h4>
                <p class="card-text"><?php echo $ca['dateScored'];?></p>
                <!-- <a href="/images/Compliance%20Audit%20Report.pdf" class="card-link">View</a> -->
                <input onclick="location.href='/Controllers/report.php?auditID=<?php echo $ca['auditID'];?>'" type=submit class="btn btn-outline-primary" name="view" value="View">
                <input type="submit" class="btn btn-outline-primary" name="download" value="Download">
            </div>
        </div></form>
            <br/>
        <?php }
        ?>
    </div>


<?php }
//Admin page
if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'A'))
{
    require_once('Views/template/header.phtml');

 }

//Scorer page
if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'S'))
{
    require_once('Views/template/header.phtml'); ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <form action="<?php echo $_SERVER["PHP_SELF"] ?>" method="post">
    <div class="container">
        <h2>Assigned Audits:</h2>
        <?php
            $unscoredAudits = $view->unscoredAudits;
            foreach ($unscoredAudits as $unscoredAudit)
        { ?>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><?php echo $unscoredAudit['location'];?></h4>
                <p class="card-text">Created: <?php echo $unscoredAudit['dateCreated'];?></p>
                <input onclick="location.href='/Controllers/scoring.php?auditID=<?=$unscoredAudit['auditID']?>';" type=button class="btn btn-outline-primary" name="scoreAudit" value="Score">
            </div>
        </div>
        <?php } ?>
    </div>
    </form>
<?php }

//Questioner page
if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'Q'))
{
    require_once('Views/template/header.phtml'); ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <form action="<?php echo $_SERVER["PHP_SELF"] ?>" method="post">
        <div class="container">
            <h2>Audits to questions:</h2>
            <?php
            //$unscoredAudits = $view->unscoredAudits;
            //foreach ($unscoredAudits as $unscoredAudit)
            //{ ?>
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Location goes here<?php //echo $unscoredAudit['location'];?></h4>
                        <p class="card-text">Created: *date* <?php //echo $unscoredAudit['dateCreated'];?></p>
                        <input onclick="//location.href='/Controllers/questioner.php?auditID=<?php //echo $unscoredAudit['auditID']?>';" type=button class="btn btn-outline-primary" name="questionAudit" value="Answer">
                    </div>
                </div>
            <?php //} ?>
        </div>
    </form>

<?php }
require_once('Views/template/footer.phtml');