<?php
require_once('../Views/template/header.phtml'); ?>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel='stylesheet' type='text/css' href='../css/scoringAndQuestioningStyle.php'/>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data" >
        <?php
        $incompleteAudit = $view->incompleteAudit; ?>
        <div class="scorerBackground">
            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <?php $audits = $incompleteAudit['audit']; ?>
                            <?php $client = $incompleteAudit['client']; ?>
                            <h3>Location: <?php echo $audits['location']; ?></h3>
                            <h3>Client: <?php echo $client['username']; ?> </h3>
                            <h3>Date: <?php echo $audits['dateCreated']; ?> </h3>

                        <p><strong class="text-danger">*</strong> = required</p>
                        <?php
                        $Categories = $incompleteAudit['questions'];
                        $questionID = 0;
                        $count = 0;
                        foreach ($Categories as $Category) { ?>
                            <hr class="scorerSeparation">

                            <h4 class="card-title card-body">Category: <?php echo $Category['catDescription']; ?></h4>
                            <?php
                            $subCategories = $Category['subCategories'];
                            foreach ($subCategories as $subCategory) {
                                ?>
                                <hr class="scorerSeparation">
                                <h5 class="card-title">Sub-Category: <?php echo $subCategory['subCatDescription']; ?></h5>
                                <?php
                                $questions = $subCategory['questions'];
                                foreach ($questions as $question) {
                                    $count = $count + 1;
                                    $questionID = $question['questionID']
                                    ?>
                                    <input hidden type="text" name="questionID<?php echo $count?>" value="<?php echo $questionID ?>">
                                    <hr class="scorerSeparation">
                                    <div class="card-body">
                                        <p><strong>Question:</strong></p>
                                        <p <?php if ($question['legalFlag'] !== null){ ?>
                                            class="text-danger"<?php } ?>><?php echo $question['questionContent']; ?></p>
                                        <?php if ($question['legalFlag'] !== null) {
                                            ?>
                                            <p>Note: This question has been flagged by an Admin:</p>
                                            <p>Flag: <strong><?php echo $question['legalFlag']; ?></strong></p>
                                        <?php } ?>
                                    </div>

                                    <div class="card-body">
                                        <p><strong><span class="text-danger">*</span>Answer the question:</strong></p>
                                        <div class="form-group shadow-textarea">
                                            <label for="answerQuestion"></label>
                                            <textarea required class="form-control z-depth-1" id="answerQuestion"
                                                      name="inputAnswer<?php echo $count; ?>" rows="3"
                                                      placeholder="Write your answer to the question above"></textarea>
                                        </div>
                                    </div>

                                    <div class="card-body">
                                        <p><strong>Comment on your answer:</strong></p>
                                        <div class="form-group shadow-textarea">
                                            <label for="commentAnswer"></label>
                                            <textarea class="form-control z-depth-1" id="commentAnswer"
                                                      name="inputComment<?php echo $count; ?>" rows="3"
                                                      placeholder="Write your comment on answer you gave above"></textarea>
                                        </div>
                                    </div>

                                    <div class="card-body">
                                    <label id="evidenceLabel<?php echo $count; ?>" for="triggerEvidence<?php echo $count; ?>">Add Evidence</label>
                                    <input id="triggerEvidence<?php echo $count; ?>" type="checkbox">
                                    <div class="evidence<?php echo $count; ?>"

                                    <p>Select evidence to upload:</p>
                                    <input type="file" name="file<?php echo $count; ?>" multiple id="file">
                                    </div>
                                    </div>
                                <?php }
                            }
                        }
                        ?>
                        <input hidden type="text" name="questionCount" value="<?php echo $count ?>">
                        <input type=submit class="btn btn-outline-primary btn btn-lg float-right " name="answerQuestions" value="Submit">
                    </div>
                </div>
                <br/>
                <div>
                </div>
            </div>
    </form>

<?php require_once('../Views/template/footer.phtml');