<html lang="eng">
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="../css/report.css">
<div class="hidden">
<?php
    $audit = $view->audit;
?>
</div>

<div class="page" size="A4">
    <img class="float-right" src="../images/addenergylogo.png" width="100" height="100" alt="Add Energy Logo">
    <p><br><br></p>
        <div class="row">
            <div class="col-sm-12">
                <h2 class="text-sm-center"><u>Compliance Audit Report</u></h2>
            </div>
        </div>
    <p><br></p>
        <!-- EZ - Return for pulling data-->
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h6>Location: <?php echo $audit['audit']['location'] ?></h6>  <!-- Return location -->
            </div>
            <div class="col-sm-3"></div>
        </div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-8">
                <h6>Date: <?php echo $audit['audit']['dateScored'] ?> </h6> <!-- Return date -->
            </div>
            <div class="col-sm-3"></div>
        </div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-8">
                <h6>Client: <?php echo $audit['user']['username'] ?></h6> <!-- Return client -->
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>
    <p><br></p>
            <div class="row">
                <div class="col-sm-12"></div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                <table class="table table-sm">
                <thead class="thead-dark">
                    <tr>
                        <th colspan="2">Category</th>
                        <th>Score</th>
                        <th>Compliance</th>
                    </tr>
                    </thead>
                    <tbody>
                    <!-- Recursive Loop 1 -->
                    <?php
                            $categories = $audit['reportContent'];
                            foreach($categories as $category) {
                    $totalScoreCount = 0;
                    $totalQuestionCount = 0;?>

                    <tr class="table-secondary">
                        <td><?php echo $category['catDescription'] ?></td> <!-- Pull the Category -->
                        <td></td>

                        <?php $subCategories = $category['subCategories'];
                        foreach ($subCategories as $subCategory) {
                            $scoreCount = 0;
                            $questions = $subCategory['questions'];
                            foreach ($questions as $question) {
                                $totalQuestionCount++;

                                $answer = $question['answer'];
                                $score = $answer['score'];
                                $scoreCount += (int)$score['score'];

                            }
                            $totalScoreCount += $scoreCount;
                        }
                        ?>
                        <td><?php $totalComplianceScore = round((($totalScoreCount / ($totalQuestionCount * 5)) * 100));
                            echo $totalComplianceScore; ?>%
                        </td> <!-- Pull scores in category and if statement using % brackets. Red > Green -->
                        <td><?php if ($totalComplianceScore <= 24) {
                                ?><l style="color: darkred;">Major Non-Compliance</l><?php
                            } elseif ($totalComplianceScore <= 49) {
                                ?><l style="color: red;">Minor Non-Compliance</l><?php
                            } elseif ($totalComplianceScore <= 74) {
                                ?><l style="color: orange;">Compliant</l><?php
                            } elseif ($totalComplianceScore <= 99) {
                                ?><l style="color: green;">Top Quartile</l><?php
                            } else {
                                ?><l style="color: lightgreen;">Best Practice</l><?php
                            } ?></td>
                        </tr>

                        <!-- Recursive Loop 2 -->
                        <?php   $subCategories = $category['subCategories'];
                                foreach($subCategories as $subCategory) {
                                    $scoreCount = 0;
                                    $questionCount = 0; ?>

                            <tr>
                                <td class="borderless"></td>
                                <td><?php echo $subCategory['subCatDescription'] ?></td>
                                <?php   $questions = $subCategory['questions'];
                                    foreach($questions as $question) {
                                        $questionCount++;

                                        $answer = $question['answer'];
                                        $score = $answer['score'];

                                        $scoreCount += (int)$score['score'];
                                   ?>

                                <?php } ?>
                                    <td>
                              <?php  $complianceScore = round((($scoreCount / ($questionCount * 5)) * 100));
                                        echo $complianceScore ?>%
                                     </td>
                                    <!-- if statement using % brackets. Red > Green -->
                                <td><?php if ($complianceScore <= 24) {
                                        ?><l style="color: darkred;">Major Non-Compliance</l><?php
                                    } elseif ($complianceScore <= 49) {
                                        ?><l style="color: red;">Minor Non-Compliance</l><?php
                                    } elseif ($complianceScore <= 74) {
                                        ?><l style="color: orange;">Compliant</l><?php
                                    } elseif ($complianceScore <= 99) {
                                        ?><l style="color: green;">Top Quartile</l><?php
                                    } else {
                                        ?><l style="color: lightgreen;">Best Practice</l><?php
                                    } ?></td>
                            </tr>

                        <?php } ?>
                        <!-- END Recursive Loop 2 -->
                    <?php } ?>
                    <!-- END Recursive Loop 1 -->
                    </tbody>
                </table>
                </div>
            </div>
</div>
<p class="break"></p>
<div class="page" size="A4">
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-sm">
                <thead class="thead-dark">
                <tr>
                    <th colspan="2">Category</th>
                    <th>Score</th>
                    <th>Compliance</th>
                </tr>
                </thead>
                <tbody>
                <!-- Recursive Loop 1 -->
                <tr class="table-secondary">
                    <td>Plant</td> <!-- Pull the Category -->
                    <td></td>
                    <td>50%</td> <!-- Pull scores in category and if statement using % brackets. Red > Green -->
                    <td>Compliant</td>
                </tr>
                <!-- Recursive Loop 2 -->
                <tr>
                    <td class="borderless"></td>
                    <td>Condition Based Maintenance</td>
                    <td>0%</td> <!-- if statement using % brackets. Red > Green -->
                    <td>Major Non-Compliance</td>
                </tr>
                <!-- END Recursive Loop 2 -->
                <!-- END Recursive Loop 1 -->
                </tbody>
            </table>
        </div>
    </div>
</div>
</html>