<?php
require_once('../Views/template/header.phtml'); ?>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <div class="container">
                <h2>Location: South China Sea oil rig #10120</h2>
                <div class="card">
                    <div class="card-body">
                <p><strong>*</strong> = required</p>
                <?php
                //$scorerAudits = $view->scorerAudits;
                //foreach ($scorerAudits as $sa)
                {?>
                            <h4 class="card-title">Category:</h4>
                            <h5 class="card-title">Sub-Category:</h5>
                            <div class="card-body">
                                <p><strong>Question:</strong></p>
                            <p>This is where question will go</p>
                            </div>
                            <div class="card-body">
                            <p><strong>Answer:</strong></p>
                            <p>This is where answer will go</p>
                            </div>
                            <div class="card-body">
                            <p><strong>Answer Comment: (if no comment don't show this part)</strong></p>
                            <p>This is where the comment of the answer will go if not null</p>
                            </div>
                            <div class="card-body">
                                <label for="inputScore"><strong>Score 1-5*</strong></label>
                                <select id="inputScore"  class="form-control" required>
                                    <option value="" selected disabled>Please select a score</option>
                                    <option title="Document not in place" value="">1</option>
                                    <option title="Document in place, content quality and update frequency could be improved" value="">2</option>
                                    <option title="Document in place, circulated, clear ownership, content quality good" value="">3</option>
                                    <option title="In place, circulated, clear ownership, updated regularly and effective" value="">4</option>
                                    <option title="In place, circulated, clear ownership, updated regularly in accordance with the Company Standard" value="">5</option>
                                </select>
                            </div>
                            <div class="card-body">
                                <p><strong>Comment on your score:</strong></p>
                                <div class="form-group shadow-textarea">
                                    <label for="scoreAnswer">Shadow and placeholder</label>
                                    <textarea class="form-control z-depth-1" id="scoreAnswer" rows="3" placeholder="Write your answer to the score you have given above here"></textarea>
                                </div>
                            </div>
                <?php } ?>
                    </div>
                </div>
                <br/>
                <input type=submit class="btn btn-outline-primary float-right" name="scoreAudit" value="Score">
            </div>
        </form>

<?php require_once('../Views/template/footer.phtml');