<?php
require_once('../Views/template/header.phtml'); ?>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../css/scoring.css">
        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <?php $unscoredAudit = $view->unscoredAudit; ?>
            <div class="scorerBackground">
            <div class="container">
                <div class="card">
                    <div class="card-body">
                        <?php $audits = $unscoredAudit['audit']; ?>
                        <?php foreach ($audits as $audit)
                        {?>
                            <?php $client = $unscoredAudit['client']; ?>
                            <h3>Location: <?php echo $audit['location']; ?></h3>
                            <h3>Client: <?php echo $client['username']; ?> </h3>
                            <h3>Date: <?php echo $audit['dateCreated']; ?> </h3>

                        <?php } ?>
                <p><strong class="text-danger">*</strong> = required</p>
                <?php
                $Categories = $unscoredAudit['scoringContent'];
                $count = 0;
                foreach ($Categories as $Category) { ?>
                        <hr class="scorerSeparation">

                        <h4 class="card-title card-body">Category: <?php echo $Category['catDescription']; ?></h4>
                        <?php
                        $subCategories = $Category['subCategories'];
                        foreach ($subCategories as $subCategory) {
                        ?>
                        <hr class="scorerSeparation">
                        <h5 class="card-title">Sub-Category: <?php echo $subCategory['subCatDescription']; ?></h5>
                        <?php
                        $questions = $subCategory['questions'];
                        foreach ($questions as $question) {
                        $count = $count + 1;
                        ?>
                        <hr class="scorerSeparation">
                        <div class="card-body">
                            <p><strong>Question:</strong></p>
                            <p <?php if ($question['legalFlag'] !== null){ ?>
                                class="text-danger"<?php } ?>><?php echo $question['questionContent']; ?></p>
                            <?php if ($question['legalFlag'] !== null) {
                                ?>
                                <p>Note: This question has been flagged by an Admin:</p>
                                <p>Flag: <strong><?php echo $question['legalFlag']; ?></strong></p>
                            <?php } ?>
                        </div>
                        <?php
                        $answers = $question['answer'];
                        ?>
                        <div class="card-body">
                            <p><strong>Answer:</strong></p>
                            <p><?php echo $answers['content']; ?></p>
                        </div>
                        <?php if ($answers['comment'] !== null) {
                        ?>
                        <div class="card-body">
                            <p><strong>Answer Comment:</strong></p>
                            <p><?php echo $answers['comment']; ?></p>
                        </div>
                        <?php }

                        if($answers['evidence'] !== null) {
                            $evidences = $answers['evidence'];
                            foreach ($evidences as $evidence) { ?>

                                <div class="card-body">
                                    <p><strong>Evidence:</strong></p>
                                    <?php if ($evidence['type'] == "Image") { ?>
                                        <img src="<?php echo $evidence['path']; ?>" alt="answer evidence"
                                             style="width:300px;">
                                    <?php } ?>
                                </div>
                            <?php }
                        }
                        ?>

                        <div class="card-body">
                            <label for="inputScore"><strong>*Score 1-5</strong></label>
                            <select id="inputScore" class="form-control" name="inputScore<?php echo $count; ?>"
                                    required>
                                <option value="" selected disabled>Please select a score</option>
                                <option title="<?php echo $question['oneMark']; ?>" value="1">1</option>
                                <option title="<?php echo $question['twoMark']; ?>" value="2">2</option>
                                <option title="<?php echo $question['threeMark']; ?>" value="3">3</option>
                                <option title="<?php echo $question['fourMark']; ?>" value="4">4</option>
                                <option title="<?php echo $question['fiveMark']; ?>" value="5">5</option>
                            </select>
                        </div>
                        <div class="card-body">
                            <p><strong><span class="text-danger">*</span>Comment on your score:</strong></p>
                            <div class="form-group shadow-textarea">
                                <label for="scoreAnswer"></label>
                                <textarea required class="form-control z-depth-1" id="scoreAnswer"
                                          name="inputComment<?php echo $count; ?>" rows="3"
                                          placeholder="Write your answer to the score you have given above here"></textarea>
                            </div>
                        </div>
                        <?php }
                        }
                }
                ?>
                        <input type=submit class="btn btn-outline-primary btn btn-lg float-right " name="scoreAudit" value="Score">
                    </div>
                </div>
                <br/>
                <div>
                </div>
            </div>
            </div>
        </form>

<?php require_once('../Views/template/footer.phtml');