<!DOCTYPE html>
<html lang="en">
<head>
    <title>Add Energy</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<link rel="stylesheet" href="/css/client.css">
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="/index.php">
        <img src="/images/addenergylogo.png" alt="logo" style="width:40px;">
    </a>

    <!-- Links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/Controllers/logout.php">Logout</a>
        </li>
        <li class="nav-item">
            <?php if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'A'))
            {?>
                <a class="nav-link">You are logged in as <?php echo $_SESSION['username'];?></a>
                <?php
            }
            if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'C'))
            {?>
                <a class="nav-link">You are logged in as <?php echo $_SESSION['username'];?></a>
                <?php
            }
            if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'S'))
            {?>
                <a class="nav-link">You are logged in as <?php echo $_SESSION['username'];?></a>
                <?php
            }
            if(isset($_SESSION['loggedIn']) && ($_SESSION['accessLevel'] == 'Q'))
            {?>
                <a class="nav-link">You are logged in as <?php echo $_SESSION['username'];?></a>
                <?php
            }
            ?>
        </li>
    </ul>
</nav>
</body>
</html>



